"""
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1+2+3+4+5+6+7=28
The first ten terms would be:
    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
    
Let us list the factors of the first seven triangle numbers:
    1: 1
    3: 1,3
    6: 1,2,3,6
   10: 1,2,5,10
   15: 1,3,5,15
   21: 1,3,7,21
   28: 1,2,4,7,14,28
 
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""

import numpy as np

def prime_factors(n):
    factors = []

    while n % 2 == 0:
        factors.append(2)
        n //= 2
        
    for i in range(3,np.sqrt(n).astype(int),2):
        while n % i == 0:
            factors.append(i)
            n //= i

    if n > 1:
        factors.append(n)
        
    return np.prod(np.unique(factors,return_counts=True)[1] + 1)

#print(prime_factors(28))

# t(n) = n*(n+1)/2
divs = 0
i = 2
tri = 0 
tridvs = 0
while divs < 500:
    tri = i * (i+1) // 2
    tridvs = prime_factors(tri)
    divs = tridvs if tridvs > divs else divs 
    i = i+1 if i % 2 == 0 else i+3
# print(i,tri,tridvs)
print(f"Triangle Number ({i}): {tri} | Divisors: {tridvs}")